### ISSUE TITLE
Docker-compose 

### ISSUE THREAD

**Issue by weitzer27** [Hazmi35/jukebox#749] opened 2021-10-03 17:19 UTC
When starting docker-compose up, The bot will errors out with error 133 on versions 5+

**Comment by Hazmi35** [comment] 2021-10-03 22:10
I can't reproduce this, what's your Docker and docker-compose version? also, do you use BuildKit?

**Comment by weitzer27** [comment] 2021-10-03 23:31
Docker version 20.10.8, build 3967b7d
docker-compose version 1.29.2, build unknown

I do not use BuildKit to my knowledge. I believe it is docker throwing the error.
I do not know if it is hardware related but I am running it on a RaspberryPi 3B+.

Running latest version:

> pi@raspberrypi:~/DockerComposeFile $ docker-compose up
> Creating dockercomposefile_bot_1 ... done
> Attaching to dockercomposefile_bot_1
> bot_1  |
> bot_1  |
> bot_1  | #
> bot_1  | # Fatal error in , line 0
> bot_1  | # unreachable code
> bot_1  | #
> bot_1  | #
> bot_1  | #
> bot_1  | #FailureMessage Object: 0x7e89f3a4

Running on version 5.0.0 gives a slightly different error:

> pi@raspberrypi:~/DockerComposeFile $ docker-compose up
> dockercomposefile_bot_1 is up-to-date
> Attaching to dockercomposefile_bot_1
> bot_1  |
> bot_1  |
> bot_1  | #
> bot_1  | # Fatal error in , line 0
> bot_1  | # unreachable code
> bot_1  | #
> bot_1  | #
> bot_1  | #
> bot_1  | #FailureMessage Object: 0x7edf43a4

**Comment by Hazmi35** [comment] 2021-10-04 02:51
Can you show me your docker-compose file?

Also, are you using the official Jukebox's Docker image? if yes, then can you try using the image that you build yourself? use `docker-compose build` first then `docker-compose up`

**Comment by weitzer27** [comment] 2021-10-04 03:50
I am using the official Jukebox's Docker image. 
currently attempting a build and then compose. Will up date shortly

The docker-compose is:
 `services:

  bot:
    build: "."
    env_file:
      - .env
   # image: "hazmi35/jukebox:4.44.0"
    image: "hazmi35/jukebox:latest"
    restart: unless-stopped
    volumes:
      - "./cache:/app/cache"
      - "./logs:/app/logs"
version: "2.4"
`

**Comment by Hazmi35** [comment] 2021-10-04 03:59
can you try removing `image: "hazmi35/jukebox:latest"` and see if something changes, if not, then try removing `build: "."` and add `image: "hazmi35/jukebox:latest"` back and see if that works

**Comment by weitzer27** [comment] 2021-10-04 03:59
docker-compose build  then docker-compose worked

**Comment by Hazmi35** [comment] 2021-10-04 04:04
> docker-compose build then docker-compose worked

Hmm yea, I think something is wrong with the Docker image at Docker Hub, I can't debug it tough because I don't have any ARM devices, I think I would make docker-compose build as a default

**Comment by Hazmi35** [comment] 2021-10-04 04:06
Should be fixed with 53fa6b7fbae3775fc24f286ec7c9d36073f71061

**Comment by Hazmi35** [comment] 2021-10-04 04:08
Can you please send me the output of `uname -m` in your machine?

**Comment by weitzer27** [comment] 2021-10-04 04:09
armv71

**Comment by weitzer27** [comment] 2021-10-04 04:14
Cloned the git and docker-compose up
docker-compose built it and then ran the bot without an error. 
Thanks for the fix. 
Let me know if you need anymore information or need me to test anything.

**Comment by Hazmi35** [comment] 2021-10-04 04:22
Jukebox v5.1.0's docker-compose now would always build the images instead of pulling them from the registry (but you can still do so with `docker-compose -f docker-compose.pull.yml up`) and to rebuild the image (for example, for updating the bot) you can use `docker-compose build && docker-compose up` or `docker-compose up --build`, and add `-d` on `docker-compose up` to detach after it's running.

> Let me know if you need anymore information or need me to test anything.

Sorry to bother you, but if you have time after https://github.com/Hazmi35/jukebox/actions/runs/1302127558 is done, could you try `docker-compose -f docker-compose.pull.yml up` and see if it works? report it here if it works or not, this is not required tough, but If you can do this, it is very appreciated. The rest you can leave it to me.

**Closed by Hazmi35** 2021-10-04 04:22 UTC
Labels: more info needed

**Comment by weitzer27** [comment] 2021-10-04 23:23
Works Perfectly. 

Created a new directory and added the docker-compose.pull.yml & .env files,
Then ran with `docker-compose -f docker-compose.pull.yml up -d` 

It built and ran correctly :)

**Comment by Hazmi35** [comment] 2021-10-04 23:51
> Works Perfectly.
> 
> Created a new directory and added the docker-compose.pull.yml & .env files, Then ran with `docker-compose -f docker-compose.pull.yml up -d`
> 
> It built and ran correctly :)

Thank's about that, It seems like only 5.0.1 builds who are broken on armv71, I'll try to investigate more into it later
